shaky/src/main/java/com/linkedin/android/shaky/DrawFragment.java

This fixes issue #7, where screenshots would be very small when displayed for markup,
and continue shrinking every time you went back to edit the image.
The issue seems to be caused by an incorrect screen density being used when loading
the screenshot image. This causes the image to scale to a smaller image.

Fix #7 - Small screenshots

---

shaky-sample/src/main/java/com/linkedin/android/shaky/app/ShakyApplication.java
shaky-sample/src/main/java/com/linkedin/android/shaky/app/ShakyDemo.java
shaky-sample/src/main/res/layout/activity_demo.xml
shaky-sample/src/main/res/values/strings.xml
shaky/src/main/java/com/linkedin/android/shaky/LifecycleCallbacks.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

Consumers may want to create their own UI for starting
the feedback flow, without requiring the user to shake
their device. With this change, we now expose the
Shaky class to users of the library, but with only one
public method, startFeedbackFlow().
This also updates the demo app to show how to use the
new API.
Fixes #6

Add API for manually triggering the feedback flow

---

shaky/build.gradle
shaky/src/main/java/com/linkedin/android/shaky/EmailShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java
shaky/src/test/java/com/linkedin/android/shaky/ShakyShould.java

Very rudimentary, but should address the concerns in #18 . As per the discussion in that thread, anything more sophisticated is probably overkill at this stage.
I also threw in a basic test case, but there isn't a ton of logic to begin with.
Note: this requires a minor version bump on Seismic. The new version is still from 2015, so probably not very risky, but wanted to point that out.

Fix #18: Basic support for sensitivity levels

---

shaky/build.gradle

Made it possible to test the maven publication locally. We are using this method to do dependency testing at LinkedIn.

Made it possible to test the maven publication locally

---

shaky/build.gradle

We are using this method to do dependency testing at LinkedIn. It is also useful to review and inspect maven artifacts / poms.

Made it possible to test the maven publication locally.

---

shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

shaky activity is nullable based on activity lifecycle, a direct reference to activity in a broadcast receiver is dangerous. Use application context instead.

fix calling nullable activity directly in broadcast receiver

---

shaky/src/main/java/com/linkedin/android/shaky/FeedbackActivity.java
shaky/src/main/java/com/linkedin/android/shaky/FormFragment.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

Received feedback of Shaky that the arrow icon at the end of the shaky process looks it will send the feedback but actually just goes to the next page. To avoid the confusion, these changes allow that arrow icon (send icon) to be customizable if needed

adding the option to customize the send icon

---

shaky/src/main/java/com/linkedin/android/shaky/SendFeedbackDialog.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java
shaky/src/main/res/layout-v17/shaky_popup.xml
shaky/src/main/res/layout/shaky_popup.xml

The shake delegate gets 2 additional methods for configuring the title and message of the dialog that shows when triggering feedback.

Add ability to customize title and message of shaky dialog

---

shaky-sample/src/main/res/values/styles.xml
shaky/build.gradle
shaky/src/main/res/values/shaky_styles.xml

Currently, custom styling on alert dialogs can only be applied to apps using AppCompat base themes. This patch fills the gap by setting the attribute "materialAlertDialogTheme" in Shaky's base theme.
Tested manually by verifying that the sample app works with material theme.

Fixing alert dialog styling capability in material theme

---

shaky/build.gradle
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

With Seismic allowing setting the sensor sampling rate so as to prevent requiring another user permission in Android 12. Updating shaky to use normal sensor sampling rate as opposed to the fastest sensor sampling rate.

Update seismic and other libraries and change to use sensor delay normal

---

shaky/build.gradle

TL;DR: old version no longer works due to jcenter shutdown.
Jcenter completely shutdown and the version 2.1.1 is can no longer be fetched. 
Falcon has moved maven from v 2.2.0 
[v2.2.0](https://github.com/jraska/Falcon/releases/tag/2.2.0)

Updated Falcon Library version 

---

shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

Adding a custom dialog to be shown before the feedback flow dialog fragment

adding a custom dialog

---

.github/workflows/merge-check.yml
build.gradle
gradle/publishing.gradle
gradle/wrapper/gradle-wrapper.properties
shaky-sample/build.gradle
shaky-sample/src/main/AndroidManifest.xml
shaky-sample/src/main/res/values/styles.xml
shaky/build.gradle
shaky/src/main/AndroidManifest.xml
shaky/src/main/res/values/shaky_styles.xml

This PR is intended for following:
1. Bump to latest AGP and Gradle versions
2. Add support for Android 15 on Shaky. 
3. Enable opt out of edge to edge validation until we have finalized next steps.
Generated snapshot locally:
Testing with the fix

Add support for Android 15

---

shaky-sample/src/main/java/com/linkedin/android/shaky/app/ShakyDemo.java
shaky-sample/src/main/res/layout/activity_demo.xml
shaky-sample/src/main/res/values/strings.xml
shaky/src/main/java/com/linkedin/android/shaky/ActionConstants.java
shaky/src/main/java/com/linkedin/android/shaky/FeedbackActivity.java
shaky/src/main/java/com/linkedin/android/shaky/SendFeedbackDialog.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

- Added support in `SendFeedbackDialog` to start custom flow on positive
button click of the dialog.
- Added action `ACTION_START_BUG_REPORT` to start the "Report a Bug" flow
directly.
- Added support in `Shaky` class to start the provided flow.
- Updated `FeedbackActivity` to directly launch the Bug Report screen
when required.
- Added "Manually start bug report" button in sample app to test the
`ACTION_START_BUG_REPORT` action manually in shaky.
Tested locally. Please refer the screen-recordings below:
| Before | After |
| - | - |
| <video src="https://github.com/user-attachments/assets/00f6695c-1cab-435c-a727-b2090f8d9088"> | <video src="https://github.com/user-attachments/assets/08298ca5-16ae-4230-8ab9-a98cfc76235a"> |

Add support to perform custom action in feedback dialog

---

shaky-sample/build.gradle
shaky-sample/src/main/java/com/linkedin/android/shaky/app/ShakyDemo.java
shaky/src/main/java/com/linkedin/android/shaky/FeedbackActivity.java
shaky/src/main/res/values/shaky_styles.xml

Add support for Android 16 edge-to-edge
- Enabled edge-to-edge for FeedbackActivity and sample app.
- Added dependency for `androidx.activity:activity:1.10.1` in `shaky-sample`
to be bale to get edge to edge support in sample app.
- Used insets to handle edge to edge functionality.
- Made other required changes accordingly.
Tested locally. Please refer the attached screenrecordings:
|Theme | Before | After |
| -- | -- |--|
| Light | <video src ="https://github.com/user-attachments/assets/59debb0a-d497-47f5-8bec-475c37365b78"> | <video src="https://github.com/user-attachments/assets/c21a6011-aee0-4a35-bd09-07b05e326205">|
| Dark | <video src = "https://github.com/user-attachments/assets/e01a30f7-9666-4780-ac1e-e7a8a1b9f630"> | <video …

Add support for Android 16 edge-to-edge

---

shaky/src/main/java/com/linkedin/android/shaky/CollectDataTask.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java

Update code to not delete existing screenshots
- Updated `CollectDataTask` to not delete any existing screenshots.
- This is to avoid failure when trying to access old screenshots in
scenarios like multiple network requests.

Update code to not delete existing screenshots

---

gradle/publishing.gradle

OSS Sonatype portal was deprecated on June 30th. Now all repositories are handled under central sonatype portal. 
Changing URLs to point to central sonatype based on this doc: https://central.sonatype.org/publish/publish-portal-api/

Update central sonatype URLs

---

shaky/src/main/java/com/linkedin/android/shaky/ScreenCaptureManager.java

```java.lang.IllegalStateException: Must register a callback before starting capture, to manage resources in response to MediaProjection states.```
Adding callback prevents this crash.

Add callback to fix crash

---

shaky-sample/src/main/java/com/linkedin/android/shaky/app/ShakyDemo.java
shaky-sample/src/main/res/layout/activity_demo.xml
shaky-sample/src/main/res/values/strings.xml
shaky/src/main/java/com/linkedin/android/shaky/ActionConstants.java
shaky/src/main/java/com/linkedin/android/shaky/BottomSheetFeedbackItem.java
shaky/src/main/java/com/linkedin/android/shaky/BottomSheetFeedbackTypeAdapter.java
shaky/src/main/java/com/linkedin/android/shaky/FeedbackActivity.java
shaky/src/main/java/com/linkedin/android/shaky/ShakeDelegate.java
shaky/src/main/java/com/linkedin/android/shaky/Shaky.java
shaky/src/main/res/drawable-hdpi/shaky_dismiss.xml
shaky/src/main/res/layout/shaky_feedback_bottomsheet.xml
shaky/src/main/res/layout/shaky_single_row.xml
shaky/src/main/res/values/shaky_dimens.xml
shaky/src/main/res/values/shaky_strings.xml
shaky/src/main/res/values/shaky_styles.xml

Create bottom sheet for shake-to-feedback and launch them when shake is detected
- Created following supporting files for handling bottom sheet support:
- `BottomSheetFeedbackItem`: data wrapper to store content to be displayed for single row in bottomsheet.
- `BottomSheetFeedbackTypeAdapter`: RecyclerView.Adapter for the select type of feedback view.
- `shaky_feedback_bottomsheet`: bottomsheet's xml containing RV to show options.
- `shaky_dismiss`: Dismiss icon.
- Added support in `Shaky` to detect shake and launch bottom sheet accordingly.
- Made changes to manually launch the bottom sheet in the sample app by adding a button on the main screen i.e. `activity_demo.xml`.
- Updated `ShakyApplication` and `ShakeDelegate` to add methods for setting theme and boolean to handle bottomsheet …

Create bottom sheet for shake-to-feedback and launch them when shake is detected

---

shaky/src/main/java/com/linkedin/android/shaky/Shaky.java

- Below changes are done for navigating user to email screen directly from bottom sheet ensuring secure files attachments and collected data.
- Added a new boolean flag `isBottomSheetFlowActive` to handle this new navigation.
- Updated `Shaky#createCallback` to skip launching `FeedbackActivity` and start email screen after data collection.
- We cannot use `ShakeDelegate#shouldUseBottomSheet()` for handing this new navigation as it breaks the old feedback flow navigations.
| Before | After |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/c37328ec-92c4-437d-93fc-2b41195d6e59"> | <video src="https://github.com/user-attachments/assets/6867d63d-929c-490a-9fdc-bba7888138c0"> |

Navigate user to email screen directly from bottom sheet
